name: deploy on ubuntu
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v5
      - name: Deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.Host_IP}}
          username: ${{secrets.Host_name}}
          key: ${{secrets.Secret_Key}}
          port: 22
          
